[build]
publish = "public"
command = "hugo --minify"

[dev]
framework = "hugo" # or "#static" to force a static server
command = "npm run start"

[context]

[context.production]

[context.production.environment]
HUGO_VERSION = "0.73.0"
HUGO_ENV = "production"
GO_VERSION = "1.14"
NODE_VERSION = "10.13.0"

[context.deploy-preview.environment]
HUGO_VERSION = "0.73.0"

[context.deploy-preview]
command = "hugo --minify -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --minify -b $DEPLOY_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.73.0"

[context.master]
command = "hugo --minify -b $DEPLOY_URL"

[context.master.environment]
HUGO_VERSION = "0.73.0"